# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

treebuilder_cpp <- function(data, config) {
    .Call('_imptree_treebuilder_cpp', PACKAGE = 'imptree', data, config)
}

traindata_cpp <- function(ptree) {
    .Call('_imptree_traindata_cpp', PACKAGE = 'imptree', ptree)
}

hasRoot_cpp <- function(ptree) {
    .Call('_imptree_hasRoot_cpp', PACKAGE = 'imptree', ptree)
}

predict_cpp <- function(ptree, newdata, evalconfig) {
    .Call('_imptree_predict_cpp', PACKAGE = 'imptree', ptree, newdata, evalconfig)
}

treeInformation_cpp <- function(ptree) {
    .Call('_imptree_treeInformation_cpp', PACKAGE = 'imptree', ptree)
}

