# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_imptree_rcpp_hello_world', PACKAGE = 'imptree')
}

timesTwo <- function(x) {
    .Call('_imptree_timesTwo', PACKAGE = 'imptree', x)
}

maxIndexInSet <- function(array, set) {
    .Call('_imptree_maxIndexInSet', PACKAGE = 'imptree', array, set)
}

fcmp <- function(x, y) {
    .Call('_imptree_fcmp', PACKAGE = 'imptree', x, y)
}

